name: Create Release

on:
  push:
    paths:
      - 'BCX Assets/**'
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Zip directory
        run: zip -r BCX_Assets.zip 'BCX Assets'

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=tag::$TAG"
      
      - name: Parse latest tag
        id: parse_tag
        run: |
          IFS='.' read -ra VERSION_PARTS <<< "$TAG"
          MAJOR="${VERSION_PARTS[0]}"
          MINOR="${VERSION_PARTS[1]}"
          NEW_MINOR=$(echo "$MINOR + 1" | bc)
          NEW_TAG="$MAJOR.$NEW_MINOR"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const releaseName = 'New Release';
            const releaseBody = 'Release Notes';

            const newTag = '${{ steps.parse_tag.outputs.new_tag }}';

            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: newTag,
              name: releaseName,
              body: releaseBody
            });

            const uploadUrl = response.data.upload_url;

            const releaseId = response.data.id;

            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              name: 'BCX_Assets.zip',
              data: fs.readFileSync('BCX_Assets.zip')
            });
