name: Create Release

on:
  push:
    paths:
      - 'BCX Assets/**'
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip directory
        run: zip -r BCX_Assets.zip 'BCX Assets/'

      # Add a step to commit and push the zip file
      - name: Commit and push zip file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add BCX_Assets.zip
          git commit -m "Add BCX Assets zip file"
          git push
