name: Create Release on Main Changes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release zip
        run: |
          shopt -s extglob
          zip -r release.zip !(.github)
        if: ${{ !contains(github.event.head_commit.modified, '.github/') }}

      - name: Upload release zip
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip
