name: Create Release

on:
  push:
    paths:
      - 'BCX Assets/**'
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip directory
        run: find 'BCX Assets/' -type f -print | zip BCX_Assets.zip -@

      - name: Get latest release
        id: get_latest_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const response = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const latestRelease = response.data[0];
            const latestTag = latestRelease ? latestRelease.tag_name : 'v1.0';
            console.log('Latest Tag:', latestTag);
            const versionParts = latestTag.split('.');
            let major = 1;
            let minor = 0;
            if (latestRelease) {
              major = parseInt(versionParts[0]);
              minor = parseInt(versionParts[1]);
            }
            const newMinor = minor + 1;
            const newTag = `v${major}.${newMinor}`;
            console.log('New Tag:', newTag);
            console.log('Release Body:', latestRelease ? latestRelease.body : 'Initial Release');

            core.setOutput('new_tag', newTag);
            core.setOutput('release_body', latestRelease ? latestRelease.body : 'Initial Release');

      - name: Create Release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const releaseName = 'New Release';
            const releaseBody = '${{ steps.get_latest_release.outputs.release_body }}';
            const newTag = '${{ steps.get_latest_release.outputs.new_tag }}';

            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: newTag,
              name: releaseName,
              body: releaseBody
            });

            const uploadUrl = response.data.upload_url;

            const releaseId = response.data.id;

            // Upload the release asset
            await github.repos.uploadReleaseAsset({
              url: uploadUrl,
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              name: 'BCX_Assets.zip',
              data: Buffer.from('BCX_Assets.zip').toString('base64')
            });
