name: Create Release

on:
  push:
    paths:
      - 'BCX Assets/**'
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Zip directory
        run: zip -r BCX_Assets.zip 'BCX Assets'

      - name: Create Release
        id: create_release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const releaseName = 'New Release';
            const releaseBody = 'Release Notes';

            const response = await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v1.0',
              name: releaseName,
              body: releaseBody
            });

            const uploadUrl = response.data.upload_url;

            // Get the release ID
            const releaseId = response.data.id;

            // Upload the zip file as a release asset
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              name: 'BCX_Assets.zip',
              data: fs.readFileSync('BCX_Assets.zip')
            });
